---
name: Lint
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install pre-commit
        run: pip install pre-commit
      - name: linting
        run: pre-commit run --all-files
